services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend-runner
    environment:
      NODE_ENV: production
      API_PORT: 3333
      API_HOST: 0.0.0.0
      DATABASE_URL: file:./prisma/prisma/dev.db
    volumes:
      - ./prisma/prisma:/app/prisma/prisma
    ports:
      - "3333:3333"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-runner
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000
      NEXT_PUBLIC_API_BASE_URL: http://backend:3333
    depends_on:
      - backend
    ports:
      - "3000:3000"
